### ISSUE TITLE
Saltlake details show no data since 2023-02-08

### ISSUE THREAD

**Issue by Sembeth** [toconspiracy/storj-stats#3]
**Describe the bug**
If you scroll down to "Saltlake details" at https://storjstats.info/d/storj/storj-network-statistics?orgId=1, you will see "No data" instead of a graph. Please note that the absolute time range should be from 2023-02-08 00:00:00 to 2023-03-05 23:59:59. If the absolute time range is set from 2023-02-07 00:00:00 to 2023-03-05 23:59:59, then data will be displayed.

Since your dashboard is working fine but the stats are missing, I wasn't sure if I should report this here or elsewhere.

**To Reproduce**
1. Go to https://storjstats.info/d/storj/storj-network-statistics?orgId=1
3. Scroll down to 'Saltlake details'
4. "No data" is displayed for:
-  "Healthy Pieces Saltlake (Median)" https://storjstats.info/d/storj/storj-network-statistics?orgId=1&from=1677525060989&to=1678129860989&viewPanel=542 
- "Healthy Pieces Saltlake (Min)" https://storjstats.info/d/storj/storj-network-statistics?orgId=1&from=1677525071387&to=1678129871387&viewPanel=543
- "Healthy Pieces Saltlake" https://storjstats.info/d/storj/storj-network-statistics?orgId=1&from=1677525079730&to=1678129879730&viewPanel=546

**Expected behavior**
The graphs should display data.

**Screenshots**
![image](https://user-images.githubusercontent.com/46921730/223205958-def590b8-52fe-4cb1-a1c1-2540034bd257.png)

**Desktop (please complete the following information):**
 - Browser: Chrome 64 Bit, Edge
 - Version: [Version 1.48.171 Chromium: 110.0.5481.177 (Offizieller Build) (64-Bit)]

**Comment by toconspiracy** [comment]
Perfectly fine here :) I will need to check that, thanks for Reporting!

**Comment by toconspiracy** [comment]
Good catch, perfectly fine here, i need to check that!

**Comment by toconspiracy** [comment]
Seems the Sourcedata is sending null for those Metrics, not much i can do about it:
https://stats.storjshare.io/data.json
`storage_median_healthy_pieces_count":null,"storage_min_healthy_pieces_count":null,`

Last successfull Reporting was at 07.02.2023 19:00

**Comment by Sembeth** [comment]
Hello, as I suspected the problem is not with your dashboard.

May I suggest that you open an issue on https://github.com/storj/storj? Maybe the satellite is no longer sending the metrics. If you prefer, I can also open the issue.

**Comment by Sembeth** [comment]
Hello @toconspiracy 
I have just created an issue on https://github.com/storj/storj/issues/5657.

I will report when the issue is resolved.

**Comment by Sembeth** [comment]
Hello @toconspiracy,
the Storj team has solved the problem and the data is back.

Thank you for your great dashboard.

**Comment by toconspiracy** [comment]
Thanks for taking care of it! Was on holidays so not so much time to check that out in detail :)
