### ISSUE TITLE
New metrics available

### ISSUE THREAD

**Issue by Sembeth** [toconspiracy/storj-stats#4]
**New metrics available**
Hello, just wanted to let you know that new metrics are available.
**storage_free_capacity_estimate_vetted_bytes**
**storage_total_bytes_after_expansion** 

You may be able to add these at a later date. This is more of a notification than a request.

https://forum.storj.io/t/publicly-exposed-network-data-official-statistics-from-storj-dcs-satellites/14103/36

**Comment by toconspiracy** [comment]
Yes, i saw those new Metrics too, will take care of them soon.

**Comment by toconspiracy** [comment]
New Metrics are now gatheret, i have already created some Graphs within the WIP Dashboards:

https://storjstats.info/d/storj-wip/storj-network-statistics-wip?orgId=1
